### ISSUE TITLE
student_id in problem_builder_answer table?

### ISSUE THREAD

**Issue by danielmcquillen** [open-craft/problem-builder#149]
This could be really obvious, if so apologies.

The values stored in my `problem_builder_answer` table for the `student_id` column are varchar(32)  look like this: `5e84393e0e8ad145ea9d9c94d33bb45b`. 

But they should be int(11) to match the id table on auth_users, shouldn't they?

When I try to do a join like 
```
sql_cmd = "select pba.id, pba.name, pba.student_input, pba.created_on, pba.modified_on " \
                  "from problem_builder_answer pba, auth_user u " \
                  "where pba.student_id = u.id " \
                  "and u.id='{0}' " \
                  "and pba.course_key='{1}'".format(user_id, course_key)
```
I'm not getting the right data.

**Comment by danielmcquillen** [comment]
Aha. I see now that the table `student_anonymoususerid` for student_id. However, if I'm trying to get the student's username, is there an update to my SQL command below you'd recommend to get the student's username or real name, without joining three tables (which is probably a bit expensive).

```
        sql_cmd = "select distinct u.id " \
                  "from problem_builder_answer pba, student_anonymoususerid u " \
                  "where u.anonymous_user_id = pba.student_id and pba.course_key='{}'".format(course_key)
```

**Comment by danielmcquillen** [comment]
I'll close this issue as it's not really a bug. I'll move my request for help to Slack or elsewhere. Thanks for this great XBlock!

**Comment by bradenmacdonald** [comment]
Thanks for the updates. I believe joining three tables is necessary unfortunately.
