### ISSUE TITLE
Remove copyright footer from all problems

### ISSUE THREAD

**Issue by stvstnfrd** [open-craft/problem-builder#182]
Hey all,

We enjoy the XBlock and have started playing around with it on our instances.
One deal-breaker for our use though is the inclusion of the copyright footer on all components:

>  Copyright © 2013–2015 OpenCraft, Harvard, edX, McKinsey, and The People's Science, released under the APGLv3 license 

Is this a strict product requirement on your end or would you be open to removing this text?

For the time being, we're able to selectively hide it with a bit of CSS,
but wondered if it can be removed outright;
we'd prefer not to fork the repo.

```css
.xblock .mentoring .copyright {
  display: none;
}
```

Let us know what you think and/or if there's a reason for including this.

**Comment by stvstnfrd** [comment]
CC: @mondiaz

**Comment by bradenmacdonald** [comment]
@antoviaque Thoughts? I think this is one of the only xblocks to do this, and I do find it weird to have that in the courseware. What do you think about showing it only in the repo/readme, and/or only in Studio and not the LMS?

@stvstnfrd Even if we end up being required to keep that in, you could put that override into your theme CSS, so that there's no need to fork the repo.

**Comment by stvstnfrd** [comment]
Thanks @bradenmacdonald .

> you could put that override into your theme CSS

Yeah, we're already doing this, just hoping for one less thing to maintain ;)

And we figured if it jumped out to us, maybe others in the community would benefit from the change. Either way, thanks for looking into it.

**Comment by antoviaque** [comment]
@bradenmacdonald I think it would be fine to put a configuration toggle for this - it would have the same effect as the CSS rule, but would at least be maintainable.

@stvstnfrd Would you be willing to contribute it? :)

Technically though the AGPL license, used by most XBlocks, requires to include the copyright _somewhere_. This isn't specific to the Problem Builder XBlock, and the only reason why it's in the middle of the courseware is that there is currently no mechanism to indicate this licensing info automatically in a "About" page, for example. But the legal obligation remains, and the comment for this configuration flag should mention it imho.

**Comment by gabor-boros** [comment]
@antoviaque What should we do with this issue? Should we open a ticket on our side to put a configuration toggle for this or should we close this ticket as the related PR is already merged?

**Comment by antoviaque** [comment]
@gabor-boros It's fine to close this - someone can contribute a feature flag, but we wouldn't dedicate budget for this.
