### ISSUE TITLE
Some messages are marked as translatable but are not collected

### ISSUE THREAD

**Issue by mahyard** [open-craft/problem-builder#198]
Hi every one,
I don't know how did you collected marked message strings in .po files. but I have to notice you that some strings are missed. I think the issue is with mako templates. for example I want to point to messages from [this file](https://github.com/open-craft/problem-builder/blob/master/problem_builder/templates/html/mentoring_attempts.html). You can see that they aren't in any of .po files.

**Comment by bradenmacdonald** [comment]
@mahyard [That's an underscore template](https://github.com/open-craft/problem-builder/blob/b2495b40608da7be137ac6391bec96cd21257501/problem_builder/public/js/mentoring.js#L8), not a mako template. But yes, its strings are probably missing. I don't think anyone has localized this XBlock yet, so there are still some gaps in the internationalization that nobody has fixed. There's also currently no good tool to extract strings for an XBlock repo, though some people are working on that: https://openedx.atlassian.net/wiki/spaces/COMM/pages/753532962/Native+XBlocks+Morning+Session#NativeXBlocksMorningSession-XBlockInternationalization

Pull requests welcome! We would especially welcome PRs that include localization, such as adding a Persian translation etc.

**Comment by mahyard** [comment]
#200
