### ISSUE TITLE
Integration with the Library

### ISSUE THREAD

**Issue by wwj718** [open-craft/problem-builder#223]
Can we create the problem (which build with  problem-builder)  in Content Libraries

**Comment by bradenmacdonald** [comment]
Sorry, using Problem Builder in Content Libraries is currently not supported.

**Comment by wwj718** [comment]
@bradenmacdonald  thank you， Will you plan to support it in the future?

**Comment by bradenmacdonald** [comment]
On an unrelated project, we're currently working on making major improvements to content libraries so they can support additional XBlocks like this, but I don't yet have any timeline for when that would be available. Probably end of 2019, early 2020, something like that.

**Comment by wwj718** [comment]
@bradenmacdonald  Thanks for your reply !
