### ISSUE TITLE
Django 2.2 Support

### ISSUE THREAD

**Issue by bradenmacdonald** [open-craft/problem-builder#260]
edx-platform is being upgraded to Django 2.2 and we need to ensure this package will be compatible.

edX contact is @jmbowman

**Comment by bradenmacdonald** [comment]
@xitij2000 request from edX - would you be able to (assign someone to) look into this please?

**Comment by xitij2000** [comment]
@bradenmacdonald Created BB-2061 for this. Will see if Serenity has capacity first. Is this needed in the current sprint?

**Comment by bradenmacdonald** [comment]
@xitij2000 First thing next sprint should be ok.
