### ISSUE TITLE
Duplicate question id after copying block

### ISSUE THREAD

**Issue by lunathirteen** [open-craft/problem-builder#281]
Hi!
I have `Problem Builder` block with `Long Answer` component.
When I make a copy of it, the new block has same id (Question ID)
the 1st block
![Screenshot from 2020-05-06 14-36-40](https://user-images.githubusercontent.com/20091749/81176199-7ac3fc00-8fad-11ea-909b-20a792ab2bdb.png)
and copy of it
![Screenshot from 2020-05-06 14-42-15](https://user-images.githubusercontent.com/20091749/81176260-962f0700-8fad-11ea-9fa6-082b3e563628.png)

Shouldn't new unique id generated after copy?

Thanks for any help!

**Comment by xitij2000** [comment]
@lunathirteen The way duplication works, the LMS copies over all existing data, including the question ids, so unfortunately this is unavoidable. You will need to manually update the copied block.

**Comment by lunathirteen** [comment]
@xitij2000 Thank you for answer!
