### ISSUE TITLE
Not being able to submit answers with submit buttons.

### ISSUE THREAD

**Issue by Anniesonny** [open-craft/problem-builder#285]
After writing the answers fully, the submit button appeared below the answer box and after clicking the submit button, the submission did not proceed.

**Comment by xitij2000** [comment]
@Anniesonny  Do you see any error messages in the UI in the logs?

**Comment by Anniesonny** [comment]
No sir,
There were no error messages. It was more like the submit button doesn't work, because after clicking the button there were no changes on the page except the submit button wasn't allowed to click more than twice. Also, after the submission, a model answer is supposed to show be under the submitted answer but the model answer did not appear.

**Comment by gabor-boros** [comment]
Hello @Anniesonny 👋 
Is this problem solved/is this issue still relevant?

**Comment by gabor-boros** [comment]
@Anniesonny In case of no input I'll close this stale issue.

FYI: @arbrandes

**Comment by Anniesonny** [comment]
Sir the problem is now relevant to me because it’s too late and the I
received help late.

**Comment by gabor-boros** [comment]
@Anniesonny  Sorry for the late response on this! Anyways, thank you for getting back to reply.
- Closing this issue
