### ISSUE TITLE
Translation is missing in installed Package

### ISSUE THREAD

**Issue by Lokiiiu** [open-craft/problem-builder#311]
Hi,

I have installed the package to edx-platform ( devstack ) as well as xblock-sdk, and found translation folder is missing inside installed package hence unable to locate config.yml at runtime.

Can someone help on this?
lms-logs : 
![image](https://user-images.githubusercontent.com/20758825/95446721-4e5a4480-097e-11eb-9fc9-b65c3cacc2fe.png)

In case of Xblock-sdk : 

![image](https://user-images.githubusercontent.com/20758825/95413351-cad23080-0948-11eb-9cc7-149696d95b85.png)

**Comment by xitij2000** [comment]
Should be fixed by https://github.com/open-craft/problem-builder/pull/316
