### ISSUE TITLE
v4.1.9 is not on PyPI

### ISSUE THREAD

**Issue by kdmccormick** [open-craft/problem-builder#322]
Hi folks.

The [latest version of xblock-problem-builder on PyPI](https://pypi.org/project/xblock-problem-builder/) is 4.1.8, even though there is a v4.1.9 tag in the repository. Could you push the latest version to PyPI?

Thanks!

**Comment by gabor-boros** [comment]
Hello @kdmccormick 👋 

Thank you for opening this Issue! That's a nice catch. Let me check this and get back to this issue.

**Comment by gabor-boros** [comment]
@kdmccormick I just uploaded the missing package. Thank you for letting us know this.

FTR: https://pypi.org/project/xblock-problem-builder/4.1.9/
