### ISSUE TITLE
On pip installing in devstack platform is failing to start

### ISSUE THREAD

**Issue by vikrantuk** [open-craft/problem-builder#327]
On pip installing xblock-problem-builder in lms and studio container,

on checking logs
`edx.devstack-juniper.master.lms |     from common.djangoapps.student.models import AnonymousUserId
edx.devstack-juniper.master.lms |   File "/edx/app/edxapp/edx-platform/common/djangoapps/student/models.py", line 130, in <module>
edx.devstack-juniper.master.lms |     class AnonymousUserId(models.Model):
edx.devstack-juniper.master.lms |   File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/db/models/base.py", line 111, in __new__
edx.devstack-juniper.master.lms |     "INSTALLED_APPS." % (module, name)
edx.devstack-juniper.master.lms | RuntimeError: Model class common.djangoapps.student.models.AnonymousUserId doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS.
`

**Comment by arbrandes** [comment]
@vikrantuk, thanks for the report!  Is this issue still present on the latest release, Koa?  How about master?

**Comment by vikrantuk** [comment]
@arbrandes I'm using Juniper release.. I was able to install problem-builder using older version( 4.1.9). Should I add that in readme file along with instructions to install xblock in devstack?

**Comment by arbrandes** [comment]
We don't usually support releases older than the current one, which is why I asked about Koa.

But it seems you already solved your problem.  Pinning it to an earlier version for an older release is what I was going to suggest. :)
