### ISSUE TITLE
Does this Run on Aspen?

### ISSUE THREAD

**Issue by con-yo** [open-craft/problem-builder#56]
Hi - will this work on Aspen or do I need to upgrade to Birch?

**Comment by bradenmacdonald** [comment]
I don't think it will work in Aspen. It requires [pure XBlock children](https://github.com/edx/edx-platform/pull/5590), and I believe that feature was added after the Aspen release process began.

**Comment by con-yo** [comment]
Thank you!  Does it work on Birch?  Or Cypress only?

Sorry for the follow up.

Rafael Reyes
Amplify
amplify.com
t. 617-794-1859
e. rreyes@amplify.com

**Comment by bradenmacdonald** [comment]
It works on Birch.

**Comment by altahoo** [comment]
Hi @bradenmacdonald,

We cut off a brach from named-release/birch.rc and installed problem builder. I could see mentoring questions getting loaded when adding new unit. However, when I tried to add new component by clicking, for example, "Long Answer", I got the following error.
<img width="888" alt="screen shot 2015-08-12 at 4 50 41 pm" src="https://cloud.githubusercontent.com/assets/9531238/9236573/b120d96e-4113-11e5-84e1-560d87fa8429.png">
I run devstack in vagrant, from the console, I saw the following errors:
<img width="1392" alt="screen shot 2015-08-12 at 4 51 09 pm" src="https://cloud.githubusercontent.com/assets/9531238/9236598/d18eed1c-4113-11e5-8a24-e7101a8efa55.png">

Also, we tried problem builder with the latest edx code and it worked just fine. So I wonder if there is anything we should add in the our current branch, which is cut off from birch. Please advise. 

Thanks.

-Ting

**Comment by bradenmacdonald** [comment]
Once you've enabled problem-builder, you need to run `paver update_db` in order to create its database tables. That should fix the problem you're seeing.

**Comment by bradenmacdonald** [comment]
And for the `for_parent` issue, you may need to update to a newer version of the `XBlock` repository.

**Comment by Kelketek** [comment]
@altahoo Is this still an issue? Or did @bradenmacdonald 's suggestion fix your problem?

**Comment by antoviaque** [comment]
@Kelketek Thanks for pinging on this - I think we can close this now.

@altahoo If this is still an issue, don't hesitate to mention it so we can reopen the issue.
