### ISSUE TITLE
Error: cannot import name StudioContainerWithNestedXBlocksMixin

### ISSUE THREAD

**Issue by mityakoval** [open-craft/problem-builder#72]
This is what I get when I'm trying to run lms or studio in my devstack after installing your XBlock:

`Error: cannot import name StudioContainerWithNestedXBlocksMixin`

**Comment by Kelketek** [comment]
@mityakoval You need to have an updated version of xblock-utils in order to use this. Did you install the packages in requirements.txt?

**Comment by mityakoval** [comment]
I followed the instructions in the XBlocks tutorial on how to deploy it and it said that all requirements were satisfied: 
`Processing /xblock_dev/problem-builder`

`Requirement already satisfied (use --upgrade to upgrade): XBlock in /edx/app/edxapp/venvs/edxapp/src/xblock (from xblock-problem-builder==2.0)`

`Requirement already satisfied (use --upgrade to upgrade): xblock-utils in /edx/app/edxapp/venvs/edxapp/src/xblock-utils (from xblock-problem-builder==2.0)`

`Requirement already satisfied (use --upgrade to upgrade): lxml in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from XBlock->xblock-problem-builder==2.0)`

`Requirement already satisfied (use --upgrade to upgrade): markupsafe in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from XBlock->xblock-problem-builder==2.0)`

`Requirement already satisfied (use --upgrade to upgrade): python-dateutil in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from XBlock->xblock-problem-builder==2.0)`

`Requirement already satisfied (use --upgrade to upgrade): pytz in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from XBlock->xblock-problem-builder==2.0)`

`Requirement already satisfied (use --upgrade to upgrade): webob in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from XBlock->xblock-problem-builder==2.0)`

`Requirement already satisfied (use --upgrade to upgrade): six in /edx/app/edxapp/venvs/edxapp/lib/python2.7/site-packages (from python-dateutil->XBlock->xblock-problem-builder==2.0)`

**Comment by antoviaque** [comment]
@mityakoval Can you try to update xblock-utils to the latest version (master branch) on https://github.com/edx/xblock-utils and let us know if that fixes it? If so it would be useful to know which version of problem-builder you're using - it might have the wrong dependency.

**Comment by mityakoval** [comment]
Well, removed `xblock-utils` folders both in  `./src/` and `./venvs/edxapp/src/`. And cloned it back from https://github.com/edx/xblock-utils
Now, when I try to upgrade with
 `sudo -u edxapp /edx/bin/pip.edxapp install problem-builder/ --upgrade` 
I get this:

`Collecting XBlock from https://pypi.python.org/packages/source/X/XBlock/XBlock-0.4.tar.gz#md5=4bab75be42b020c41e54059ee44eb101 (from xblock-problem-builder==2.0)
  Downloading XBlock-0.4.tar.gz (41kB)
    100% |################################| 45kB 5.0MB/s
Collecting xblock-utils (from xblock-problem-builder==2.0)`
`Could not find any downloads that satisfy the requirement xblock-utils (from xblock-problem-builder==2.0)`
`No distributions at all found for xblock-utils (from xblock-problem-builder==2.0)`

**Comment by Kelketek** [comment]
@mityakoval Use pip install -r requirements.txt, which has a listing of the exact install place for xblock-utils. It is not available on Pypi.

**Comment by mityakoval** [comment]
Ran `sudo pip install -r requirements.txt`.
Tried to run `paver studio` and got a lot of `DistributionNotFound` exceptions.
Here is one of them:

`DistributionNotFound: The 'xblock-utils' distribution was not found and is required by the application
2015-10-18 10:28:39,181 WARNING 2745 [xblock.plugin] plugin.py:147 - Unable to load XBlock 'pb-table'
Traceback (most recent call last):
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/plugin.py", line 144, in load_classes
    yield (class_.name, cls._load_class_entry_point(class_))
  File "/edx/app/edxapp/venvs/edxapp/src/xblock/xblock/plugin.py", line 73, in _load_class_entry_point
    class_ = entry_point.load()
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2354, in load
    self.require(*args, **kwargs)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2371, in require
    items = working_set.resolve(reqs, env, installer)
  File "/edx/app/edxapp/venvs/edxapp/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
`

**Comment by Kelketek** [comment]
@mityakoval You shouldn't use sudo pip install-- you need to install those prereqs as the edxapp user within your devstack, which has its own Python environment. Drop the sudo, do it as the edxapp user.

**Comment by mityakoval** [comment]
Thanks, I've managed to run studio without any errors, and I can see Problem Builder module in Advanced. But I can't add any elements or it just not quite obvious how to do it. It says that the block contains multiple components, but when I try to click any of them nothing happens. Do I need to install anything else?

**Comment by Kelketek** [comment]
You shouldn't need to install anything else. You click the 'view' button to get to the components under the problem builder block, and you click the green buttons underneath to add different components from there. If there's a traceback somewhere, or a JS error that appears to be happening within the problem-builder JS, let us know.

**Comment by antoviaque** [comment]
Sounds like the original issue is fixed, so closing this ticket.
